name: fintech_wiorx
version: '1.0.0'
config-version: 2

profile: fintech_wiorx

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fintech_wiorx:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
