services:
  minio:
    image: minio/minio:latest
    container_name: fintech-wiorx-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    restart: unless-stopped

  mc:
    image: minio/mc:latest
    container_name: fintech-wiorx-mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
      mc mb --ignore-existing local/$$MINIO_BUCKET;
      echo Bucket created: $$MINIO_BUCKET;
      exit 0;
      "

  generator:
    build:
      context: ./generator
    container_name: fintech-wiorx-generator
    depends_on:
      - minio
      - mc
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: ["python", "main.py"]

  postgres:
    image: postgres:15
    container_name: fintech-wiorx-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: fintech
      POSTGRES_PASSWORD: fintech123
      POSTGRES_DB: fintech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbt:
    build:
      context: .
      dockerfile: docker/dbt/Dockerfile
    container_name: fintech-wiorx-dbt
    depends_on:
      - postgres
    env_file:
      - .env
      - dbt/.env
    volumes:
      - ./dbt:/usr/app
    working_dir: /usr/app
    stdin_open: true
    tty: true
    command: ["sleep", "infinity"]

volumes:
  minio_data:
  postgres_data:
